"use server";

import { createClient } from "@/utils/supabase/server";
import { revalidatePath } from "next/cache";
import { GoogleGenerativeAI } from "@google/generative-ai";

/**
 * Admin: Generate quiz content using Gemini AI (Preview only)
 */
export async function generateQuizAI(params: {
    topic: string;
    difficulty: string;
    num_questions: number;
}) {
    const supabase = await createClient();

    // 1. Verify Admin Role
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return { error: "Authentication required" };

    const { data: profile } = await supabase
        .from("profiles")
        .select("role")
        .eq("id", user.id)
        .single();

    if (profile?.role !== 'admin') return { error: "Admin access required" };

    // 2. Deep Prompting for Structured Quiz
    const prompt = `Generate a high-quality quiz about "${params.topic}" at "${params.difficulty}" difficulty.
Generate exactly ${params.num_questions} questions.

Return ONLY a valid JSON array (no markdown, no explanation) with this exact structure:
[
  {
    "question": "string",
    "options": ["string", "string", "string", "string"],
    "correct_index": 0,
    "timer_seconds": 15
  }
]`;

    try {
        // Use gemini-2.5-flash — JSON output enforced via prompt + fence-stripping
        const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);
        const model = genAI.getGenerativeModel({
            model: "gemini-2.5-flash",
        });

        // Retry up to 3 times with exponential backoff for 503 overload errors
        const MAX_RETRIES = 3;
        let lastError: any;
        let result: any;

        for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
            try {
                result = await model.generateContent(prompt);
                break; // Success — exit retry loop
            } catch (err: any) {
                lastError = err;
                const is503 = err?.message?.includes('503') || err?.message?.includes('Service Unavailable') || err?.message?.includes('high demand');
                if (is503 && attempt < MAX_RETRIES) {
                    const delay = attempt * 1000; // 1s, 2s, 3s
                    console.warn(`Gemini 503 on attempt ${attempt}/${MAX_RETRIES}. Retrying in ${delay}ms...`);
                    await new Promise(res => setTimeout(res, delay));
                    continue;
                }
                throw err; // Non-503 error or out of retries
            }
        }

        const responseText = result.response.text();

        // Clean any accidental markdown fences just in case
        const cleaned = responseText.replace(/```json[\s\S]*?```|```[\s\S]*?```/g, (s: string) =>
            s.replace(/```json|```/g, '').trim()
        ).trim();

        let quizQuestions: any[];
        try {
            quizQuestions = JSON.parse(cleaned);
        } catch (parseErr) {
            console.error("JSON parse failed. Raw response:", responseText);
            return { error: `AI returned unparseable response. Raw: ${responseText.slice(0, 200)}` };
        }

        if (!Array.isArray(quizQuestions)) {
            console.error("AI returned non-array:", quizQuestions);
            return { error: "AI returned invalid data format (expected an array)" };
        }

        // Return the content for editing in the UI
        return {
            success: true,
            data: {
                title: `${params.topic.toUpperCase()} TRIAL`,
                description: `A competitive trial generated by AEGIS AI focusing on ${params.topic}. Level: ${params.difficulty}`,
                questions: quizQuestions.map((q: any) => ({
                    questionText: q.question,
                    options: q.options,
                    correctIndex: q.correct_index,
                    timerSeconds: q.timer_seconds || 15
                }))
            }
        };

    } catch (err: any) {
        const message = err?.message || String(err);
        console.error("Gemini Quiz Generation Failed:", message);
        // Surface the actual error so it's debuggable
        return { error: `Gemini error: ${message}` };
    }
}
